#![no_std]
//! strata-compute — tier 3: computation traits.
//!
//! traits needed by nox (VM execution) and jali (ring arithmetic).
//! these represent computational capabilities beyond basic arithmetic.
//!
//! ## Spectral
//!
//! a field with roots of unity — the spectral domain exists.
//! polynomial evaluation at all N-th roots of unity simultaneously
//! (the NTT / number theoretic transform) runs in O(N log N) instead of O(N²).
//!
//! the name "spectral" comes from spectral methods in numerical analysis:
//! transform between coefficient domain and evaluation domain, compute in
//! whichever domain is cheaper, transform back. this is what NTT does
//! for polynomial multiplication in jali and polynomial jets in nox.
//!
//! Goldilocks has two-adicity 32 (p-1 is divisible by 2^32), giving
//! roots of unity up to order 2^32 — enough for polynomials up to
//! 4 billion terms. F₂¹²⁸ and F_q (CSIDH) lack this structure.
//!
//! ## Bits
//!
//! decompose field elements into bits and reconstruct from bits.
//! nox uses this for binary operations (comparison, shifts, masks).
//! Binius (lens) uses this for binary constraint encoding.

use strata_core::Field;

/// a field with spectral structure: roots of unity and NTT.
///
/// the multiplicative group F* has a subgroup of order 2^S
/// generated by the 2^S-th root of unity. this enables the
/// number theoretic transform (NTT) for O(N log N) polynomial
/// evaluation and interpolation.
///
/// not all fields are spectral:
/// - Goldilocks: yes (S = 32, 2^32-th root of unity exists)
/// - F₂¹²⁸: no (multiplicative group has order 2^128 - 1, not smooth)
/// - F_q (CSIDH): no (q-1 chosen for isogeny structure, not NTT)
/// - Tropical: not a field
pub trait Spectral: Field {
    /// two-adicity: largest k such that 2^k divides |F*|.
    /// Goldilocks: S = 32 (p - 1 = 2^32 · (2^32 - 1)).
    const TWO_ADICITY: u32;

    /// primitive 2^S-th root of unity.
    /// ω^(2^S) = 1 and ω^(2^(S-1)) ≠ 1.
    const ROOT_OF_UNITY: Self;

    /// inverse of the root of unity: ω^(-1).
    const ROOT_OF_UNITY_INV: Self;

    /// multiplicative generator of F* (a primitive root).
    const GENERATOR: Self;

    /// get a root of unity of order n.
    /// n must be a power of 2 and n ≤ 2^TWO_ADICITY.
    /// returns ω^(2^S / n) — the principal n-th root of unity.
    fn root_of_unity(n: usize) -> Self {
        assert!(n.is_power_of_two());
        let log_n = n.trailing_zeros();
        assert!(log_n <= Self::TWO_ADICITY);
        // ω^(2^S / n) = ω^(2^(S - log_n))
        let exp = 1u64 << (Self::TWO_ADICITY - log_n);
        Self::ROOT_OF_UNITY.pow(exp)
    }
}

/// decompose field elements into bits and reconstruct.
///
/// nox uses bit decomposition for comparison (lt), shifts, masks.
/// Binius uses it for binary constraint encoding (1 constraint per bit).
pub trait Bits: Field {
    /// number of bits in the canonical representation.
    const NUM_BITS: u32;

    /// decompose into little-endian bits.
    fn to_bits_le(&self) -> alloc::vec::Vec<bool>;

    /// reconstruct from little-endian bits.
    fn from_bits_le(bits: &[bool]) -> Self;
}

extern crate alloc;
